# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: thomaswong25520
google_analytics: dbyll
title: dbyll

defaults:
  - scope:
      path: "" # empty string for all files
    values:
      title: Thomas Wong Blog

description: Thomas Wong Blog
author:
  name: Thomas Wong
  email: thomaswong8321@gmail.com
  github: thomaswong25520
  # twitter: dbtek
  # pinterest: asd123
  linkedin: thowo
  bio: Technical Account Manager at Reputation
  email_md5: 726351295ec82e145928582f595aa3aa

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html
about_path: about.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
